version: '3'

services:

  php:
    build: ./php
    env_file:
      - local.env
    volumes:
      - ../:/var/www/test-task/
    networks:
      - backend

  nginx:
      build: ./nginx
      env_file:
        - local.env
      restart: always
      environment:
        - VIRTUAL_HOST=test-task.loc
      depends_on:
        - php
      volumes:
        - ../:/var/www/test-task/
      command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.nginx > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
      networks:
        - frontend
        - backend

  mysql:
    build: ./db
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: J7LtxOlr6pBHktzz
    networks:
      - backend

  phpmyadmin:
    build: ./phpmyadmin
    environment:
      - VIRTUAL_HOST=phpmyadmin.lc
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=J7LtxOlr6pBHktzz
    networks:
      - frontend
      - backend

networks:
  frontend:
    external:
      name: proxy_proxy
  backend: